version: "3.9"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=channelservice_db
    ports:
      - 5432:5432

  django:
    build:
      context: ./django
    command: gunicorn channelservice.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./django/.env
    depends_on:
      - postgres
      
  celery:
    restart: always
    build:
      context: ./django
    command: celery -A channelservice worker -l INFO
    depends_on:
      - postgres
      - redis
      - django
      
  celery_beat:
    build:
      context: ./django
    command: celery -A channelservice beat
    depends_on:
      - postgres
      - redis
      - django
      
  react:
    build:
      context: ./react
    volumes:
      - react_build:/react/build
    stdin_open: true
      
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - django
      - react

volumes:
  postgres_data:
  react_build:
