# Generated by Django 4.0.6 on 2022-07-17 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер записи')),
                ('order_number', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('dollars', models.DecimalField(decimal_places=5, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доллары США')),
                ('delivery_time', models.DateField(verbose_name='Срок поставки')),
                ('rubles', models.DecimalField(decimal_places=5, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рубли РФ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
